
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - ubuntu:22.04
      args:
        BUILDKIT_INLINE_CACHE: 1
    ports: #TODO: Adjust port for my server, change it from zero
      - "8080:8080"  
    volumes:
      - .:/app  #TODO: Adjust paths
      - build-cache:/app/build
      - vcpkg-cache:/opt/vcpkg/downloads
      - apt-cache:/var/cache/apt
    deploy:
      resources:
        limits:
          memory: 4G  #TODO: Adjust memory or remove that
  stt:
    build:
      context: ./docker/STT_server
      dockerfile: Dockerfile
    ports:
      - "8765:8765"
    volumes:
      - .:/app  
    environment:
      - DEBIAN_FRONTEND=noninteractive
      - TZ=UTC
      - PYTHONUNBUFFERED=1
  tts:
    build:
      context: ./docker/TTS_server
      dockerfile: Dockerfile
    ports:
      - "8766:8766"
    volumes:
      - .:/app  
    environment:
      - DEBIAN_FRONTEND=noninteractive
      - TZ=UTC
      - PYTHONUNBUFFERED=1
volumes:
  build-cache:
  vcpkg-cache:
  apt-cache: