services:
  tele:
    image: mlan/asterisk
    container_name: tele
    cap_add:
      - net_admin
      - net_raw
    expose:
      - "${SMS_PORT-8080}:${WEBSMSD_PORT:-80}"
      - "5060:5060/udp"
      - "5060:5060"
      - "5061:5061"
      - "10000-10099:10000-10099/udp"
    environment:
      - SYSLOG_LEVEL=4
      - HOSTNAME=tele.example.com
      - WEBSMSD_PORT=80
    volumes:
      - tele-conf:/srv
    networks:
      - app_network

  # server:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   volumes:
  #     - .:/app
  #     - build_cache:/app/build
  #   restart: unless-stopped
  #   networks:
  #     - app_network

  #   whisper:
  #     build:
  #       context: .
  #       dockerfile: Dockerfile
  #     expose:
  #       - "8080"
  #     volumes:
  #       - .:/app
  #       - build_cache:/app/build
  #     restart: unless-stopped
  #     networks:
  #       - app_network
    
  #   tts:
  #     build:
  #       context: .
  #       dockerfile: Dockerfile
  #     expose:
  #       - "8081"
  #     volumes:
  #       - .:/app
  #       - build_cache:/app/build
  #     restart: unless-stopped
  #     networks:
  #       - app_network

networks:
  app_network:
    driver: bridge

volumes:
  # build_cache:
  tele-conf: